//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class logout
{
    protected global::System.Web.UI.HtmlControls.HtmlForm form1;
}
}