//------------------------------------------------------------------------------
// <auto-generated>
//------------------------------------------------------------------------------

public partial class staff
{
    protected global::System.Web.UI.HtmlControls.HtmlForm form1;

    protected global::System.Web.UI.WebControls.TextBox txtSearch;

    protected global::System.Web.UI.WebControls.Label lblMyAssets;

    protected global::System.Web.UI.WebControls.Label lblReports;

    protected global::System.Web.UI.WebControls.Label lblDepartments;

    protected global::System.Web.UI.WebControls.Button btnViewReport;

    protected global::System.Web.UI.WebControls.Button btnFindAsset;
}